/**
 * LLM brief 생성 — Claude Sonnet 4.6 + prompt caching + Vault context.
 *
 *   npm run brief                  # 최신 snapshot
 *   npm run brief -- --file=...    # 특정 snapshot
 *
 * 출력:
 *   - Vault: 300_Resources/Crypto Dashboard/insights/<DATE>_brief.md
 *   - Vault: 300_Resources/Crypto Dashboard/_signals/latest_brief.md (포인터)
 */

import "dotenv/config";
import fs from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

import { generateBrief } from "../lib/wiki/claude.ts";
import { summarizeSnapshot, type SnapshotFile } from "../lib/wiki/snapshot-summary.ts";
import { ensureVaultStructure, PATHS, readNote, writeNote, readUserNotes, sourceBriefPath } from "../lib/wiki/vault.ts";
import { splitByMarkers } from "../lib/wiki/markers.ts";
import { buildFrontmatter } from "../lib/wiki/frontmatter.ts";
import { briefSourceFrontmatter } from "../lib/wiki/templates.ts";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = path.resolve(__dirname, "..", "..");
const SNAPSHOT_DIR = path.join(REPO_ROOT, "data", "snapshots");

async function findLatestSnapshot(): Promise<string> {
  const files = await fs.readdir(SNAPSHOT_DIR);
  const json = files.filter((f) => f.endsWith(".json")).sort();
  if (json.length === 0) throw new Error("No snapshots in data/snapshots/. Run `npm run snapshot` first.");
  return path.join(SNAPSHOT_DIR, json.at(-1)!);
}

function isoToShortDate(iso: string): string {
  const d = new Date(iso);
  return `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, "0")}-${String(d.getDate()).padStart(2, "0")}`;
}

/**
 * LLM-Wiki에서 사용자가 작성한 entity 페이지의 본문(자동 영역 외)을 수집.
 * 코인/기관 entity에 사용자가 추가 메모를 작성했으면 LLM context로 활용.
 *
 * crypto-future-finance 도메인 페이지 + Crypto-Dashboard 프로젝트 인덱스도 포함.
 */
async function collectVaultUserContext(): Promise<string> {
  const sections: string[] = [];

  // 도메인 페이지
  const domain = await readNote(PATHS.domainCryptoFinance);
  if (domain) {
    sections.push(`### domains/crypto-future-finance.md\n\n${domain.slice(0, 4000)}`);
  }

  // 프로젝트 인덱스 (생성됐다면)
  const proj = await readNote(PATHS.projectCryptoDashboard);
  if (proj) {
    const split = splitByMarkers(proj);
    sections.push(`### projects/Crypto-Dashboard.md (프로젝트 메타)\n\n${split.preamble + split.postamble}`);
  }

  // entities 폴더 — 사용자가 본문(자동 영역 외)에 추가 메모를 작성한 entity만 수집
  const notes = await readUserNotes(PATHS.entities, 200);
  for (const { filename, content } of notes) {
    const split = splitByMarkers(content);
    const userPart = (split.preamble + split.postamble).trim();
    // 본문의 의미 있는 텍스트만 (헤더·테이블·자동생성 라인 제외)
    const meaningful = userPart
      .split("\n")
      .filter((l) => {
        const trimmed = l.trim();
        if (!trimmed) return false;
        if (trimmed.startsWith("#")) return false;
        if (trimmed.startsWith(">")) return false;
        if (trimmed.startsWith("|")) return false;
        if (trimmed.startsWith("---")) return false;
        if (trimmed.startsWith("*(")) return false; // *(LLM이 ingest 시 보강)*
        return true;
      })
      .join("\n");
    if (meaningful.length > 80) {
      sections.push(`### entities/${filename}\n\n${userPart.slice(0, 3000)}`);
    }
  }

  return sections.join("\n\n---\n\n");
}

async function main(): Promise<void> {
  const args = process.argv.slice(2);
  const fileArg = args.find((a) => a.startsWith("--file="))?.split("=")[1];
  const snapshotPath = fileArg ?? (await findLatestSnapshot());

  console.log(`📖 Snapshot: ${path.relative(REPO_ROOT, snapshotPath)}`);

  await ensureVaultStructure();

  const raw = await fs.readFile(snapshotPath, "utf-8");
  const snapshot = JSON.parse(raw) as SnapshotFile;
  const date = isoToShortDate(snapshot.timestamp);

  const snapshotSummary = summarizeSnapshot(snapshot);
  const vaultContext = await collectVaultUserContext();

  console.log(`📚 Vault user context: ${vaultContext.length} chars`);
  console.log(`📊 Snapshot summary: ${snapshotSummary.length} chars`);
  console.log(`🤖 Generating brief with Claude Sonnet 4.6...`);

  const result = await generateBrief({ snapshotSummary, vaultContext, date });

  console.log();
  console.log(`   Model: ${result.model}`);
  console.log(`   Input tokens: ${result.usage.input_tokens}`);
  console.log(`   Cache read: ${result.usage.cache_read_input_tokens ?? 0}  ·  Cache write: ${result.usage.cache_creation_input_tokens ?? 0}`);
  console.log(`   Output tokens: ${result.usage.output_tokens}`);

  // LLM-Wiki에 source로 저장 (wiki/sources/<date>_Crypto-Signal-Brief.md)
  const briefPath = sourceBriefPath(date);
  const fm = briefSourceFrontmatter(date);
  const header = [
    buildFrontmatter(fm),
    `# Crypto Signal Brief — ${date}`,
    "",
    `> Generated by ${result.model}.  Snapshot: \`${path.basename(snapshotPath)}\``,
    `> Cache hit: ${result.usage.cache_read_input_tokens ?? 0} tokens · write: ${result.usage.cache_creation_input_tokens ?? 0} · fresh input: ${result.usage.input_tokens} · output: ${result.usage.output_tokens}`,
    "",
    "**관련 자료**: [[Crypto-Dashboard]] · [[crypto-future-finance]] · [[" + date + "]] (daily-signals)",
    "",
    "---",
    "",
  ].join("\n");
  await writeNote(briefPath, header + result.markdown + "\n");

  console.log();
  console.log(`✅ wiki/sources/${date}_Crypto-Signal-Brief.md`);
  console.log(`   Vault: ${path.relative(process.env.HOME ?? "", PATHS.root)}`);
}

main().catch((err) => {
  console.error("\n❌ Brief 생성 실패");
  console.error((err as Error).message);
  process.exit(1);
});
