/**
 * Weekly Brief — 주 1회 자동 회고.
 *
 *   npm run weekly                  # 기본 7일치
 *   npm run weekly -- --days=14     # 14일치
 *
 * 출력:
 *   - wiki/briefings/<YYYY-Www>_weekly-brief.md (Vault에 저장)
 *   - 텔레그램으로 짧은 TL;DR 발송 (TELEGRAM_*가 있으면)
 *
 * GitHub Actions에서 매주 일요일 KST 21:00 (UTC 12:00) 자동 실행 권장.
 */

import "dotenv/config";
import fs from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

import { aggregateWeekly, summarizeForLLM } from "../lib/wiki/weekly-summary.ts";
import { generateWeeklyBrief } from "../lib/wiki/weekly-claude.ts";
import { ensureVaultStructure, PATHS, readNote, writeNote, readUserNotes } from "../lib/wiki/vault.ts";
import { splitByMarkers } from "../lib/wiki/markers.ts";
import { buildFrontmatter } from "../lib/wiki/frontmatter.ts";
import { sendTelegram } from "../lib/notify/telegram.ts";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = path.resolve(__dirname, "..", "..");

interface CliArgs {
  days: number;
}

function parseArgs(): CliArgs {
  const args = process.argv.slice(2);
  const get = (key: string) => args.find((a) => a.startsWith(`--${key}=`))?.split("=")[1];
  return { days: Number(get("days") ?? 7) };
}

function isoWeekKey(d: Date = new Date()): string {
  // ISO Week (W01-W53) — Monday-anchored
  const target = new Date(d.valueOf());
  const dayNr = (d.getUTCDay() + 6) % 7;
  target.setUTCDate(target.getUTCDate() - dayNr + 3);
  const firstThursday = target.valueOf();
  target.setUTCMonth(0, 1);
  if (target.getUTCDay() !== 4) {
    target.setUTCMonth(0, 1 + ((4 - target.getUTCDay()) + 7) % 7);
  }
  const weekNo = 1 + Math.ceil((firstThursday - target.valueOf()) / 604800000);
  return `${d.getUTCFullYear()}-W${String(weekNo).padStart(2, "0")}`;
}

async function collectVaultContext(): Promise<string> {
  const sections: string[] = [];

  // 도메인 (참조용)
  const domain = await readNote(PATHS.domainCryptoFinance);
  if (domain) sections.push(`### domains/crypto-future-finance.md\n\n${domain.slice(0, 3000)}`);

  // 프로젝트 인덱스
  const proj = await readNote(PATHS.projectCryptoDashboard);
  if (proj) {
    const split = splitByMarkers(proj);
    sections.push(`### projects/Crypto-Dashboard.md (사용자 메모)\n\n${(split.preamble + split.postamble).trim()}`);
  }

  // entities — 사용자가 본문에 메모 작성한 것만
  const notes = await readUserNotes(PATHS.entities, 100);
  for (const { filename, content } of notes) {
    const split = splitByMarkers(content);
    const userPart = (split.preamble + split.postamble).trim();
    const meaningful = userPart
      .split("\n")
      .filter((l) => {
        const t = l.trim();
        return t && !t.startsWith("#") && !t.startsWith(">") && !t.startsWith("|") && !t.startsWith("---") && !t.startsWith("*(");
      })
      .join("\n");
    if (meaningful.length > 80) {
      sections.push(`### entities/${filename}\n\n${userPart.slice(0, 2000)}`);
    }
  }

  return sections.join("\n\n---\n\n");
}

async function main(): Promise<void> {
  const { days } = parseArgs();
  console.log(`📊 Weekly Brief 생성 (지난 ${days}일)`);

  await ensureVaultStructure();

  // 1. 주간 데이터 집계
  const summary = await aggregateWeekly(REPO_ROOT, days);
  const summaryText = summarizeForLLM(summary);
  console.log(`📦 ${summary.totalSnapshots} snapshots / ${summary.signalChanges.length} 시그널 변경 / ${summary.closedPlans.length} 청산 plans / ${summary.activePlans.length} 활성 plans`);

  // 2. Vault context 수집
  const vaultContext = await collectVaultContext();
  console.log(`📚 Vault context: ${vaultContext.length} chars`);

  // 3. LLM brief
  const dStart = summary.rangeStart.slice(0, 10);
  const dEnd = summary.rangeEnd.slice(0, 10);
  const weekRange = `${dStart} → ${dEnd}`;
  console.log(`🤖 Claude Sonnet 4.6 brief 생성...`);
  const result = await generateWeeklyBrief({ weekRange, summaryText, vaultContext });

  console.log(`   model=${result.model}  cache_read=${result.usage.cache_read_input_tokens ?? 0}  fresh=${result.usage.input_tokens}  output=${result.usage.output_tokens}`);

  // 4. Vault에 저장
  const wkey = isoWeekKey(new Date(summary.rangeEnd));
  const briefFile = path.join(PATHS.briefings, `${wkey}_weekly-brief.md`);
  const fm = buildFrontmatter({
    title: `Weekly Brief ${wkey}`,
    type: "overview",
    domain: "crypto-future-finance",
    tags: ["weekly-brief", "회고", "6렌즈", "x-vip-portfolio"],
    created: dEnd,
  });
  const header = [
    fm,
    `# Weekly Brief — ${wkey} (${weekRange})`,
    "",
    `> Generated by ${result.model}.  Snapshots: ${summary.totalSnapshots}.  Closed plans: ${summary.closedPlans.length}.  Active: ${summary.activePlans.length}.`,
    "",
    `**관련**: [[Crypto-Dashboard]] · [[crypto-future-finance]]`,
    "",
    "---",
    "",
  ].join("\n");
  await writeNote(briefFile, header + result.markdown + "\n");
  console.log(`✅ ${path.relative(REPO_ROOT, briefFile)}`);

  // 5. 텔레그램으로 짧은 요약 발송
  if (process.env.TELEGRAM_BOT_TOKEN && process.env.TELEGRAM_CHAT_ID) {
    const tgText = [
      `📊 *Weekly Brief — ${wkey}*`,
      ``,
      result.shortSummary,
      ``,
      `_Vault: briefings/${wkey}_weekly-brief.md_`,
    ].join("\n");
    const tgRes = await sendTelegram({ text: tgText, parseMode: "Markdown" });
    if (tgRes.ok) console.log(`📨 Telegram TL;DR 발송 (msg ${tgRes.messageId})`);
    else console.log(`⚠️ Telegram 발송 실패: ${tgRes.error}`);
  }
}

main().catch((err) => {
  console.error("❌ Weekly Brief 실패");
  console.error((err as Error).message);
  process.exit(1);
});
